### ISSUE TITLE
Unable to display the diagrams using .ecorediag files

### ISSUE THREAD

**Issue by yridene** [dice-project/DICE-Models#13]
The diagrams can't be properly displayed (please see attached file).

![invalidview](https://cloud.githubusercontent.com/assets/13781987/11527066/f85656ec-98de-11e5-9358-f06ce4f546bf.png)

**Comment by abelgomez** [comment]
I don't have this issue, the models are properly displayed in my setup.

For the icons I see, could it be possible that you are using a different version of the Ecore Tools plugin? They have to be opened with Ecore Tools 1.2 (http://download.eclipse.org/modeling/emft/ecoretools/updates/1.2/201306071421), and the icon of the diagram file should be ![icon](https://cloud.githubusercontent.com/assets/5593904/11529504/cda1b234-98ed-11e5-83ff-acd1f12bd5c3.png).

**Comment by maelstromdat** [comment]
Ciao Youssef!!! I haven’t looked into the issue but I think Abel is right, you may require some additional plugins.. try evaluating if all of the models are shown like that, if so, then you may definitely require more plugins

**Comment by yridene** [comment]
I checked my plugins and I have already EcoreTools plugins (cf. screenshot) but a newer version (3.0)
![ecore diagram editor](https://cloud.githubusercontent.com/assets/13781987/11978771/52e6f93a-a98e-11e5-9a7d-b504e010f985.png)
![ecoretools](https://cloud.githubusercontent.com/assets/13781987/11978770/52e29098-a98e-11e5-99c2-158a82d21413.png)
![eclipse marketplace_2015-12-23_16-00-30](https://cloud.githubusercontent.com/assets/13781987/11978772/52f546e8-a98e-11e5-80ae-49161f47aed4.png)

.

**Comment by abelgomez** [comment]
Then is a version issue.

As I said, the models MUST be opened using EcoreTools v1.x, that is available in the UpdateSite I said. The technologies used by EcoreTools 3.x differ from the 1.x branch.

The full-fledged Ecore Editor provided by EcoreTools 3.x is based on Sirius. The Ecore editor provided by EcoreTools 1.x is directly based on GMF.

The editor you are using in EcoreTools 3.x is based on GMF too, but is not the exact same one that the one of v1.x, and expects a different graphical representation (*.ecore_diagram)

Blame Damian for using that version ;)

**Comment by yridene** [comment]
Thanks Abel for this detailed explanation. As an end-user (use case provider), I'll use Papyrus instead :)
