### ISSUE TITLE
StorageNode class in DPIM has been renamed to StorageStorageNode

### ISSUE THREAD

**Issue by abelgomez** [dice-project/DICE-Models#2]
`StorageNode` class in DPIM has been renamed to `StorageStorageNode` in the last version of the DPIM.

Is this a typo and should this change be reverted (i.e., rename to StorageNode)?

**Comment by maelstromdat** [comment]
this is a typo that our Student Saeed committed while adapting the MMs for model-transformation, I found a lot and solved many of them but some may have slipped away... I guess you can simply remove the additional "Storage" :)
